var fakeData =
    [
        {id: 4589, instructor: 'Jhankar Vhai', name: 'HTML full course', price: 1500, img: 'https://i.ibb.co/w4ty9sc/html.png', description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos iste architecto commodi odit quae illo velit voluptates dolore, fuga iure laborum unde dignissimos vel ut officia reiciendis adipisci optio. Molestias.'}, 
        {id: 3489, instructor: 'Manik Vhai', name: 'Pure Javascript full course', price: 3000, img: 'https://i.ibb.co/RHvzhQv/js.png', description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos iste architecto commodi odit quae illo velit voluptates dolore, fuga iure laborum unde dignissimos vel ut officia reiciendis adipisci optio. Molestias.'}, 
        {id: 3796, instructor: 'Shadhin Vhai', name: 'Bootstrap full course', price: 2000, img: 'https://i.ibb.co/vLc23Vf/bootstrap.png', description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos iste architecto commodi odit quae illo velit voluptates dolore, fuga iure laborum unde dignissimos vel ut officia reiciendis adipisci optio. Molestias.'}, 
        {id: 7441, instructor: 'Reja Vhai', name: 'Angular JS full course', price: 5000, img: 'https://i.ibb.co/M1mTvtr/angular.png', description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos iste architecto commodi odit quae illo velit voluptates dolore, fuga iure laborum unde dignissimos vel ut officia reiciendis adipisci optio. Molestias.'}, 
        {id: 4547, instructor: 'Kumu Apu', name: 'C++ full course', price: 1000, img: 'https://i.ibb.co/VYPn4wT/cpp.png', description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos iste architecto commodi odit quae illo velit voluptates dolore, fuga iure laborum unde dignissimos vel ut officia reiciendis adipisci optio. Molestias.'}, 
        {id: 6541, instructor: 'Rasel Vhai', name: 'Django full course', price: 4500, img: 'https://i.ibb.co/CPLGFk1/django.webp', description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos iste architecto commodi odit quae illo velit voluptates dolore, fuga iure laborum unde dignissimos vel ut officia reiciendis adipisci optio. Molestias.'}, 
        {id: 7596, instructor: 'Jhankar Vhai', name: 'Java full course', price: 8000, img: 'https://i.ibb.co/c8g97b3/java.webp', description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos iste architecto commodi odit quae illo velit voluptates dolore, fuga iure laborum unde dignissimos vel ut officia reiciendis adipisci optio. Molestias.'}, 
        {id: 4175, instructor: 'Manik Vhai', name: 'Mongo DB full course', price: 5500, img: 'https://i.ibb.co/mXLbWNb/mongo.webp', description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos iste architecto commodi odit quae illo velit voluptates dolore, fuga iure laborum unde dignissimos vel ut officia reiciendis adipisci optio. Molestias.'}, 
        {id: 4789, instructor: 'Shadhin Vhai', name: 'Mysql full course', price: 6300, img: 'https://i.ibb.co/q9Fmwt0/mysql.jpg', description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos iste architecto commodi odit quae illo velit voluptates dolore, fuga iure laborum unde dignissimos vel ut officia reiciendis adipisci optio. Molestias.'}, 
        {id: 5974, instructor: 'Reja Vhai', name: 'Node JS full course', price: 8500, img: 'https://i.ibb.co/825bRP0/node.jpg', description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos iste architecto commodi odit quae illo velit voluptates dolore, fuga iure laborum unde dignissimos vel ut officia reiciendis adipisci optio. Molestias.'}, 
        {id: 5644, instructor: 'Kumu Apu', name: 'PHP full course', price: 4700, img: 'https://i.ibb.co/fCDjGGM/php.png', description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos iste architecto commodi odit quae illo velit voluptates dolore, fuga iure laborum unde dignissimos vel ut officia reiciendis adipisci optio. Molestias.'}, 
        {id: 4125, instructor: 'Rasel Vhai', name: 'Python full course', price: 10000, img: 'https://i.ibb.co/YNB5B7h/python.png', description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos iste architecto commodi odit quae illo velit voluptates dolore, fuga iure laborum unde dignissimos vel ut officia reiciendis adipisci optio. Molestias.'}, 
        {id: 4974, instructor: 'Jhankar Vhai', name: 'React JS full course', price: 12200, img: 'https://i.ibb.co/Wn9WW4F/react.png', description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos iste architecto commodi odit quae illo velit voluptates dolore, fuga iure laborum unde dignissimos vel ut officia reiciendis adipisci optio. Molestias.'}, 
        {id: 6554, instructor: 'Manik Vhai', name: 'Vue JS full course', price: 7900, img: 'https://i.ibb.co/N9vcdWy/vue.png', description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos iste architecto commodi odit quae illo velit voluptates dolore, fuga iure laborum unde dignissimos vel ut officia reiciendis adipisci optio. Molestias.'}, 
        {id: 7854, instructor: 'Shadhin Vhai', name: 'CSS full course', price: 7900, img: 'https://i.ibb.co/cLkv6S2/css.png', description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos iste architecto commodi odit quae illo velit voluptates dolore, fuga iure laborum unde dignissimos vel ut officia reiciendis adipisci optio. Molestias.'}, 

    ];

export default fakeData;